###########################
#                         #
#      API LOG IN         #
#                         #
###########################
#POST 
POST http://localhost:3001/api/sessions

###
GET http://localhost:3001/api/sessions/current

###
DELETE http://localhost:3001/api/sessions/current

#######################################
#                                     #
#       METHOD ON LOCAL PLANE         #
#                                     #
#######################################
#GET to obtain seats
GET http://localhost:3001/api/local
###

#######################################
#                                     #
#       METHOD ON REGIONAL PLANE      #
#                                     #
#######################################
#GET to obtain seats
GET http://localhost:3001/api/regional
###



#######################################
#                                     #
#    METHOD ON INTERNATIONAL PLANE    #
#                                     #
#######################################
#GET to obtain seats
GET http://localhost:3001/api/international
###

#############################
#                           # 
#    API RESERVE SEATS      #
#                           #
#############################
GET http://localhost:3001/api/bookings/1

###

###
POST http://localhost:3001/api/bookings
content-type : application/json

{
  "IdUser": 2,
  "PlaneType": "international",
  "Seats": [
    {
      "Id": 1,
      "Column": "A"
    }
  ]
}
###
DELETE http://localhost:3001/api/bookings
content-type : application/json

{
  "IdUser" : 1,
  "AirplaneType" : "international"
}
###

